dbt_project:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dinosauria-499515
      dataset: staging
      threads: 4
      location: US-EAST1
      keyfile: /opt/airflow/keys/gcp-service-account.json
  target: dev